rosbag record \
/docking/command \
/docking/lock_command \
/docking/state \
/docking/target_pose \
/docking/uav_path \
/docking/path_marker \
/docking/state_marker \
/docking/target_arrow \
/docking/target_cube \
/uav/arrow_marker \
/uav/mesh_marker \
/endoscope_cam/camera_info \
/endoscope_cam/image_raw \
/mavros/imu/data \
/mavros/local_position/pose \
/mavros/local_position/velocity_local \
/mavros/setpoint_velocity/cmd_vel \
/mavros/vision_pose/pose \
/mavros/state \
/navsat/fix \
/tag_detections \
/tag_detections_image/compressed \
/uav/realsense_D435i/color/camera_info \
/uav/realsense_D435i/color/image_raw/compressed \
/uav/realsense_D435i/depth/camera_info \
/uav/realsense_D435i/depth/image_raw \
/tf \
/clock \
/jackal_velocity_controller/cmd_vel \
/jackal_velocity_controller/odom \
/odometry/filtered \
-o ${MISSION_NAME}